arch: arm32

os: linux

addons:
  firefox: latest

language: python
python:
  - "2.7"

services:
  - docker

install:
- pip install -r requirements.txt
- bash early_tests.sh
- wget 'https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz'
- tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
- sudo mv geckodriver /usr/local/bin
- # docker-compose pull backend
- ./keep_alive.sh 120 docker-compose build

script:
- bash docker_test.sh

deploy:
  provider: script
  script: bash -c '{ echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin > /dev/null 2>&1; } && bash docker_push.sh'
  on:
    branch:
      - VideoCaption
