name: CI

on:
  push:
    branches:
    - VideoCaption
    - actions
    - speedo
 
  pull_request:
    branches:
    - VideoCaption 
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
      - uses: actions/checkout@v2

      - name: Docker Pull
        run: |
          bash docker_hub.sh pull
           
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          bash early_tests.sh
          sudo apt-get install firefox
          wget 'https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz'
          tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin

      - name: Build
        run: |
          bash docker_build.sh
          
      - name: Test
        run: |
          bash docker_test.sh

      # Push image to docker on 'push' event only.
      - name: Deploy to Docker Hub
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        env:
          DOCKER_USERNAME: "scopeinfinity"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          { echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin ; } && bash docker_hub.sh push
