name: CI

on:
  push:
    branches: [ VideoCaption actions ]
  pull_request:
    branches: [ VideoCaption ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies, build and execute test
        run: |
          pip install -r requirements.txt
          bash early_tests.sh
          sudo apt-get install firefox
          wget 'https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz'
          tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin
          docker-compose pull backend
          ./keep_alive.sh 120 docker-compose build
          bash docker_test.sh

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: "scopeinfinity"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          { echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin ; } && bash docker_push.sh
